### ISSUE TITLE
部署后没有把所有部署的合约加到abi storage里去

### ISSUE THREAD

**Issue by leonlianght** [ObsidianLabs/ConfluxStudio#10]
部署后没有把所有部署的合约加到abi storage里去，只加了第一个合约。(我是部署一个部署合约，部署合约会自动部署其他4个合约，这四个合约必须我手工加到abi storage里)

**Comment by qftgtr** [comment]
From version 0.3.3, you can right-click an ABI JSON file to deploy and the ABI will be added automatically.
