### ISSUE TITLE
Bug:M1芯片合约部署

### ISSUE THREAD

**Issue by xuwuo** [ObsidianLabs/ConfluxStudio#152]
### Description

transaction timeout : pengdingTransaction.mined not a function

### Is IDE

Yes

### Client

Desktop

### How to reproduce

编译
部署

### Actual result

transaction timeout : pengdingTransaction.mined not a function

### Error log

transaction timeout : pengdingTransaction.mined not a function

**Comment by iNorthIsle** [comment]
@xuwuo hi，the latest version has resolved the issue
