### ISSUE TITLE
Fail to run docker...

### ISSUE THREAD

**Issue by tranhoaison** [ObsidianLabs/ConfluxStudio#16]
Here is the error: ![image](https://user-images.githubusercontent.com/31094102/92401828-abcd5c80-f158-11ea-85d0-763d7494803d.png)

My docker can run without sudo:
![image](https://user-images.githubusercontent.com/31094102/92401929-e505cc80-f158-11ea-9183-c90ef5aa3b4e.png)

**Comment by leonlianght** [comment]
https://docs.docker.com/engine/install/linux-postinstall/

**Comment by leonlianght** [comment]
You will need to set up Post-installation steps for Linux.
https://docs.docker.com/engine/install/linux-postinstall/

Because Studio use 'docker' instead of 'sudo docker', you will need to add a unix group for it.

**Comment by tranhoaison** [comment]
> You will need to set up Post-installation steps for Linux.
> https://docs.docker.com/engine/install/linux-postinstall/
> 
> Because Studio use 'docker' instead of 'sudo docker', you will need to add a unix group for it.

Thanks for replying. I have followed the introductions. But I still get the same errors.

**Comment by leonlianght** [comment]
Did you restart the docker service?

try `sudo restart docker`

**Comment by tranhoaison** [comment]
Even I restarted my PC, It doesn't work.

**Comment by qftgtr** [comment]
Could you please run `docker info` and `docker -v` in the terminal and paste the results?

**Comment by tranhoaison** [comment]
**Docker info:**

```
Client:
 Debug Mode: false

Server:
 Containers: 15
  Running: 0
  Paused: 0
  Stopped: 15
 Images: 2
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-45-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.57GiB
 Name: sonth-desktop
 ID: 7JJD:2CPN:2TNN:QI4I:NRUQ:GSK5:3VGJ:6ZAB:E7Z2:MMUB:5SGV:JKET
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Docker -v:** 
`Docker version 19.03.12, build 48a66213fe`

_p/s: I'm using ubuntu 20.04:_

```
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 8
model name	: AMD Ryzen 5 2600 Six-Core Processor
stepping	: 2
microcode	: 0x800820d
cpu MHz		: 2793.527
cache size	: 512 KB
physical id	: 0
siblings	: 12
core id		: 0
cpu cores	: 6
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov 
pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp
 lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclm
ulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdran
--More--(0%)

```

**Comment by leonlianght** [comment]
We've located the issue. The last line `WARNING: No swap limit support` in `docker info` raises an error but it actually doesn't affect docker's normal operation. We skipped all warnings when checking the docker in the [new version](https://github.com/ObsidianLabs/ConfluxStudio/releases/tag/v0.3.2).
