### ISSUE TITLE
Bug: 编译1155合约后没有deploy按钮

### ISSUE THREAD

**Issue by l42111996** [ObsidianLabs/ConfluxStudio#177]
### Description

mac系统 在编译完合约之后选中对应的json文件右键无法出现deploy按钮

<img width="311" alt="image" src="https://user-images.githubusercontent.com/4860185/175524866-66b7d2a6-71c2-4613-9118-dd7162ebc19b.png">

### Is IDE

Yes

### Client

Desktop

### How to reproduce

monterey下载conflux studio和vs code，用vscode编译，然后在confluxstudio里面点击对应的json文件右键无法出现deploy按钮

### Actual result

deploy按钮未出现

### Error log

系统版本monterey，

### Expected result

出现deploy按钮

**Comment by Whisper22X** [comment]
Thank you for your feedback.   We have reported the problem to our technical department. 
You can temporarily deploy using Deploy in the Project menu bar.

**Comment by l42111996** [comment]
already found，thanks for your help
