### ISSUE TITLE
Feature request: Show revert reason when available

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#20]
In recent Solidity versions, you can add a reason string to require statements:

```solidity
function foo() payable public {
    require(msg.value > 0, "Value insufficient");
    ...
}
```

This error shows up in Remix like this:

```
transact to Contract.foo errored: VM error: revert. revert The transaction has been reverted to the initial state.
Reason provided by the contract: "Value insufficient". Debug the transaction to get more information.
```

It would be nice if Conflux Studio could also show the revert reason, when available. Decoding this value might involve an additional contract call, as outlined in [this](https://blog.8bitzen.com/posts/31-10-2019-how-to-get-require-error-message-with-web3j) blog post.

Additional, somewhat related changes:
- Please add option to show the whole receipt for failed transactions.
- Typo: `transaction "0x..." executed failed, outcomeStatus 1`: `executed` --> `execution`

**Comment by Thegaram** [comment]
This info might be exposed on the node RPC in a future release (see [conflux-rust#1841](https://github.com/Conflux-Chain/conflux-rust/pull/1841) and follow-up PRs).

**Comment by qftgtr** [comment]
This feature is added in release v0.4.1.
