### ISSUE TITLE
Feature request: Shortcut for commenting lines of code

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#21]
In most (all?) editors, when I select a number of lines and press `Cmd` + `/`, it comments out the lines.

Before:

```solidity
function foo() {
    // ...
}
```

After:

```solidity
// function foo() {
//     // ...
// }
```

This is very useful, please consider adding it to your editor.

**Comment by qftgtr** [comment]
This is fixed and will be release in v0.12.0
