### ISSUE TITLE
Feature request: Choose which contract to deploy

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#22]
Let's say I have `contract A` in `A.sol`. If I rename it to `contract B` and click Deploy, it will still deploy the old version (the previously compiled `A.json`) instead of the new one (`B.json`) as that is the one specified in `config.json`.

It would be nice if, in this case, Deploy would allow me to change whether I want to deploy `A` or `B`.

**Comment by qftgtr** [comment]
resolved
