### ISSUE TITLE
Bug: Unnamed event field seems to cause crash

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#24]
When I deploy this contract and query for `Event`s, the UI just *disappears* (i.e. I see a blank grey window).

```solidity
pragma solidity >=0.5.0 <0.7.0;

contract Contract {
    event Event(uint256);

    constructor() public {
        emit Event(0);
    }
}
```

**Comment by qftgtr** [comment]
The crash issue is fixed now. However, the `uint256` type does not display correctly due to Conflux-Chain/js-conflux-sdk#82.
