### ISSUE TITLE
Bug: Cannot deploy contract with no constructor

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#25]
When I try to deploy a contract with no constructor, I get this error: `Error in reading the ABI. No constructor found.`

To reproduce, compile and deploy this contract:

```solidity
pragma solidity ^0.5.0;

contract Contract {
    function foo() public payable {
        // empty
    }
}
```

Conflux Studio v0.3.3
Conflux Truffle v0.0.8

**Comment by Thegaram** [comment]
I think this is still not fixed. I get `"Cannot read property 'obj' of undefined"` on v.0.4.1 (solc 7.1). @qftgtr

**Comment by qftgtr** [comment]
Yeah, we noticed that and added another fix in v0.4.2 as pre-release yesterday. I'll keep this issue open until we cover all the cases.

**Comment by Thegaram** [comment]
Seems like you're one step ahead of me! Thank you.

**Comment by qftgtr** [comment]
should resolved now
