### ISSUE TITLE
Feature request: Various minor UX enhancements

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#28]
Allow closing pup-up windows using Escape. This includes windows like `Deploy Contract` and `Deployment Result`.

**Comment by Thegaram** [comment]
Here's a similar issue. It's very minor so I decided not to open a new issue.

Let's say I selected a field:

![image](https://user-images.githubusercontent.com/7571518/94172497-da567180-fe92-11ea-969e-e90c6d32708c.png)

When I press `Tab`, I would expect to jump to the next field. Instead, it first jumps onto that type indicator on the left (which is not very useful):

![image](https://user-images.githubusercontent.com/7571518/94172514-de828f00-fe92-11ea-8fb5-061d19454570.png)

**Comment by Thegaram** [comment]
Similarly to closing modals by `Esc`, modals should be submitted when hitting `Enter` (e.g. on the Deploy contract page).

**Comment by Thegaram** [comment]
Should allow reordering tabs. This includes tabs for open files on the editor page and contract instances on the Contracts page.

**Comment by Thegaram** [comment]
When creating a new file, the new file should be opened automatically after I click Create.

**Comment by qftgtr** [comment]
Esc and Tab buttons work now.

We don't think enter key is a good choice because users may accidentally trigger it, and they may also need to use it in a textarea input.
