### ISSUE TITLE
Docker image improvement

### ISSUE THREAD

**Issue by leonlianght** [ObsidianLabs/ConfluxStudio#30]
发现在conflux studio中启动一个实例然后停止，docker container中就没有这个实例了；那也就是说这个是conflux studio来管理创建与删除的。
看到conflux studio 也提供了docker image的创建与删除的管理。
但是conflux studio 不能完全控制docker image的生命周期，所以就会出现在根据之前的container启动历史记录创建container时由于image缺失出现的问题。
我觉得既然conflux studio不能完全控制docker image的生命周期，那么这里conflux studio可以通过以下方法解决该问题：
检查container对应image是否存在，如果存在可以直接启动，否则提示用户image已丢失，提供一个重新下载的按钮和删除该实例的按钮

**Comment by qftgtr** [comment]
Resolved in v0.4.0.
