### ISSUE TITLE
Feature request: Highlight errors and warnings in editor

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#32]
It would be nice if errors and warnings from solc would appear in the editor. The simplest way is to highlight the corresponding line. This is the way Remix does it for errors:

![image](https://user-images.githubusercontent.com/7571518/94157227-47f9a200-fe81-11ea-8de6-0100671395c5.png)

... and for warnings:

![image](https://user-images.githubusercontent.com/7571518/94157296-5f388f80-fe81-11ea-801a-f8b6fd74d2da.png)

A nice feature they have is, if I edit the file (e.g. add new lines before ` constructor`) but do not recompile, then the hightlight will follow the corresponding function.

**Comment by qftgtr** [comment]
resolved
