### ISSUE TITLE
Feature request: Improve UX for RPC errors

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#33]
When I tried to deploy a contract with gas limit set too high, I saw this:

![image](https://user-images.githubusercontent.com/7571518/94172120-64520a80-fe92-11ea-93f4-3ae738cb7001.png)

On the node output, I see this:

```
2020-09-24T16:19:44.114912515+00:00 WARN  http.worker00        cfxcore::tra - Transaction discarded due to above gas limit: 1000000000000 > 100000000
```

Looking at the node source code, I'm almost sure a similar error message is returned to the JSON-RPC caller. It would be nice if the UI could show detailed RPC errors, otherwise it's hard to debug.

**Comment by qftgtr** [comment]
Transaction errors are now displayed in the transaction detail modal.
