### ISSUE TITLE
Feature request: Add storage_limit and estimate by default

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#35]
I think contract deployments and transactions should provide a `storage_limit` field, just like we see on Conflux Portal.

It would be great if the UI could use `cfx_estimateGasAndCollateral` to give estimates. It could either populate `gas_limit` and `storage_limit` with the estimates by default, or it could provide a button to fill in the estimate (this way, values set by the user would not be overwritten).

**Comment by qftgtr** [comment]
Duplicated to 44
