### ISSUE TITLE
Bug: Cannot deploy after timeout

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#36]
My contract deploy timed out, I got a timeout error. However, the deploy button is still a loading indicator, which prevents me from deploying again

![image](https://user-images.githubusercontent.com/7571518/94174181-40dc8f00-fe95-11ea-984f-4adcf20f701a.png)

**Comment by qftgtr** [comment]
Fixed in v0.4.2
