### ISSUE TITLE
建议编译完后弹出abi跟bytecode

### ISSUE THREAD

**Issue by leonlianght** [ObsidianLabs/ConfluxStudio#38]
- cfx: 没有地方指引用户知道打开对应json，需要在提示中增加指引
- phil:熟悉truffle的人一般知道编译后的json文件在哪
- cfx: conflux studio与cfxtruffle是不同的两种产品，conflux studio只是使用cfxtruffle完成了部分工能，但使用conflux studio时不应该让用户必须学习cfxtruffle才能使用conflux studio。

**Comment by qftgtr** [comment]
resolved
