### ISSUE TITLE
当有多个合约时需要在setting中设置配置部署合约的名称，不友好

### ISSUE THREAD

**Issue by leonlianght** [ObsidianLabs/ConfluxStudio#41]
- cfx: 当前只能手动修改config.json，用户无法得知如何修改；改为有多个合约时弹出列表让用户选择；或者部署用户正在编辑的页面的合约
- phil: 右键点击编译后的JSON文件，即可部署
- cfx: 列表选择可以在下个版本迭代

**Comment by qftgtr** [comment]
Duplicated to #22

**Comment by qftgtr** [comment]
resolved
