### ISSUE TITLE
Feature request: contract interaction parameters as hex string

### ISSUE THREAD

**Issue by aalu1418** [ObsidianLabs/ConfluxStudio#48]
Right now the contract interaction for bytes32 must be inputted in utf-8. It would be very useful to also be able to give an input as a hex string starting with "0x"

Reasoning: hashes in bytes32 don't always have a good utf-8 equivalent

**Comment by Thegaram** [comment]
+1, this feature would be useful.

**Comment by qftgtr** [comment]
This is supported from v0.9.0.
