### ISSUE TITLE
Bug: Cannot send simple transaction to contract

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#50]
Cannot specify CFX to send along when deploying a contract. Also cannot send CFX directly to a contract, there's no such option under `WRITE FUNCTIONS`. For reproducing, try this contract:

```solidity
pragma solidity ^0.7.1;

contract C {
    constructor() payable { }

    receive() external payable { }

    fallback() external payable { }
}
```

When deploying a contract through a payable constructor, the deploy modal should have a `CFX to Transfer` field.

When the ABI has `receive` or `fallback`, the Contract page should expose a simple *Send CFX* method.

**Comment by qftgtr** [comment]
Resolved. We add a transfer button in the explorer and you can use it to make transfers to a contract.
