### ISSUE TITLE
v0.5.0 代付功能可能设置不成功

### ISSUE THREAD

**Issue by leonlianght** [ObsidianLabs/ConfluxStudio#65]
我们刚刚测试和定位了一下，确认了问题确实是因为 Conflux 1.0+ 以上的版本（包括测试网络）的 SponsorWhitelistControl 的函数命名从 snake case 更新成了 camel case。

当前最新版本(v0.5.0) Conflux Studio 的 SponsorWhitelistControl 默认使用的是旧版本的 snake case，因此导致了这个问题。我们将会在下一个版本对此做修复，而在此之前，可能需要使用临时的解决方案来设置代付。

目前临时解决方法是：
1. 合约部分需要将 SponsorWhitelistControl.sol 更换成 https://github.com/Conflux-Chain/conflux-rust/blob/master/internal_contract/contracts/SponsorWhitelistControl.sol，即将 snake case 变成 camel case。

2. 替换 Coin.sol 中的 add_privilege 和 remove_privilege 为 camel case 的 addPrivilege 和 removePrivilege

3. 打开 Contract 页面中的 ABI Storage，点击 New，分别填入以下信息：

Name: SponsorWhitelistControl

Code hash/address: 0x0888000000000000000000000000000000000001

ABI:
```JSON
[
  {
    "constant": false,
    "inputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "name": "addPrivilege",
    "outputs": [],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "constant": false,
    "inputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "name": "removePrivilege",
    "outputs": [],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "constant": false,
    "inputs": [
      {
        "internalType": "address",
        "name": "contract_addr",
        "type": "address"
      }
    ],
    "name": "setSponsorForCollateral",
    "outputs": [],
    "payable": true,
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "constant": false,
    "inputs": [
      {
        "internalType": "address",
        "name": "contract_addr",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "upper_bound",
        "type": "uint256"
      }
    ],
    "name": "setSponsorForGas",
    "outputs": [],
    "payable": true,
    "stateMutability": "payable",
    "type": "function"
  }
]
```

**Comment by beibeiandroid** [comment]
同时需要注意一点的是 CFX to Transfer 需要填值的，默认不填也是无法调用成功 

![image](https://user-images.githubusercontent.com/4607463/99881571-76171a80-2c55-11eb-97ed-722ae8c38127.png)

**Comment by leonlianght** [comment]
Solved in latest versoin
