### ISSUE TITLE
Events in "Coin" do not show up

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#74]
**Steps to reproduce:**
- Create a new project with the built-in Coin template.
- Deploy an instance of the contract on the Conflux Testnet.
- Call "mint".
- Call "send".

**Expected behavior:** When I query Send events, I should see one event corresponding to the latest transfer.

**Actual behavior:** No events show up.

**Comment by leonlianght** [comment]
Thanks for reporting.
We have contacted Conflux team and it seems that they are working on json-rpc of Testnet, some of the APIs are different. We will work with the Conflux team and try to solve it asap.

**Comment by leonlianght** [comment]
Should be fixed in [v0.6.0](https://github.com/ObsidianLabs/ConfluxStudio/releases/tag/v0.6.0)
