### ISSUE TITLE
Unable to send CFX on v0.6.0

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#77]
Conflux Studio v0.6.0 does not send the correct CFX amount. This is probably the root cause of #76 as well.

![image](https://user-images.githubusercontent.com/7571518/109453540-a3dcde00-7a52-11eb-864f-952cb7768a24.png)

![image](https://user-images.githubusercontent.com/7571518/109453553-accdaf80-7a52-11eb-91d0-635fbaeda4de.png)

```solidity
pragma solidity >=0.5.0 <0.7.0;

contract Coin {
    event SendCfxToContract(address, uint256);

    function sendCfxToContract() public payable {
        uint256 amount = msg.value;
        emit SendCfxToContract(msg.sender, amount);
    }
}
```

**Comment by leonlianght** [comment]
Fixed in latest version:
https://github.com/ObsidianLabs/ConfluxStudio/releases/tag/v0.7.1
