### ISSUE TITLE
Should be able to build large projects in Docker

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#85]
Many users have been unable to build large projects due to the error below.

![image](https://user-images.githubusercontent.com/7571518/117526251-7a15d980-aff6-11eb-9999-1f96af8de189.png)

A workaround is to use the default solc version (avoid using Docker). The Conflux Studio team has already looked into this, and it seems this issue is related to truffle.

In any case, this issue affects user experience. I suggest the team tries to solve this, or include some helpful error message in the next release, e.g. *"Conflux Studio is currently unable to build large projects in Docker. Please try selecting "default solc" in the bottom bar to build the project without Docker."*.

**Comment by qftgtr** [comment]
This is fixed in v0.12.0
